# Generated by Django 5.0.14 on 2025-07-11 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_author'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='post',
            new_name='post_publish_49d927_idx',
            old_name='blog_post_publish_bb7600_idx',
        ),
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
    ]
