# Generated by Django 5.0.14 on 2025-07-11 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_blog_post_publish_bb7600_idx_post_publish_49d927_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='post',
            new_name='blog_post_publish_bb7600_idx',
            old_name='post_publish_49d927_idx',
        ),
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
