# Generated by Django 5.0.14 on 2026-04-13 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(choices=[('spam', 'Spam'), ('low_value', 'Low Value'), ('worth_engaging', 'Worth Engaging')], max_length=20)),
                ('claude_reasoning', models.TextField(blank=True)),
                ('draft_reply', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('replied', 'Replied'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('classified_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-classified_at',),
            },
        ),
        migrations.CreateModel(
            name='SocialOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('twitter', 'Twitter/X'), ('reddit', 'Reddit'), ('quora', 'Quora')], max_length=20)),
                ('post_url', models.URLField(unique=True)),
                ('post_text', models.TextField()),
                ('author', models.CharField(blank=True, max_length=200)),
                ('engagement_count', models.IntegerField(default=0)),
                ('relevance_score', models.FloatField(default=0.0)),
                ('claude_reasoning', models.TextField(blank=True)),
                ('draft_reply', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('actioned', 'Actioned'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('found_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Social Opportunities',
                'ordering': ('-relevance_score', '-found_at'),
            },
        ),
        migrations.CreateModel(
            name='TranscriptQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=50, unique=True)),
                ('video_title', models.CharField(max_length=500)),
                ('channel_id', models.CharField(max_length=100)),
                ('channel_name', models.CharField(blank=True, max_length=200)),
                ('raw_transcript', models.TextField()),
                ('status', models.CharField(choices=[('raw', 'Raw'), ('processing', 'Processing'), ('draft_created', 'Draft Created'), ('failed', 'Failed')], default='raw', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-fetched_at',),
            },
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created'], name='blog_commen_created_0e6ed4_idx'),
        ),
        migrations.AddField(
            model_name='commentalert',
            name='comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert', to='blog.comment'),
        ),
        migrations.AddField(
            model_name='socialopportunity',
            name='related_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_opportunities', to='blog.post'),
        ),
        migrations.AddField(
            model_name='transcriptqueue',
            name='draft_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcript_source', to='blog.post'),
        ),
    ]
