# Generated by Django 5.0.14 on 2026-04-13 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0009_commentalert_socialopportunity_transcriptqueue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyDigest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(unique=True)),
                ('analytics_summary', models.TextField()),
                ('top_performing_article', models.CharField(blank=True, max_length=500)),
                ('recommended_content_type', models.TextField(blank=True)),
                ('search_console_insights', models.TextField(blank=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Weekly Digest',
                'ordering': ('-week_start',),
            },
        ),
        migrations.CreateModel(
            name='PostSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_description', models.CharField(blank=True, max_length=200)),
                ('suggested_tags', models.JSONField(default=list)),
                ('internal_link_notes', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='blog.post')),
            ],
            options={
                'verbose_name': 'Post SEO',
            },
        ),
    ]
